services:
  - type: web
    name: promptoid-ai
    env: node
    buildCommand: ./scripts/render-build.sh
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: promptoid-ai
          envVarKey: RENDER_EXTERNAL_URL
      - key: NEXTAUTH_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
